### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by incorpusyehtee** [victor-rds/KeeTrayTOTP#1]
I have installed the plugin (says 0.9.0.2 in the plugin manager, SHA-1 71279896b3e831a81aadba77496b024c880010dd).

When I am configuring TOTP there is no option for Steam formatted passwords, only 6 and 8 digit passwords.

I tried to change the otp string's &size= parameter to &size=S, but that did not work.

Video of the plugin's TrayTOTP pop-up http://i.imgur.com/3eshMnA.webm

Thanks much

**Comment by victor-rds** [comment]
First, sorry I was on vacation!
Now for the error, are you using the old plugin together? They conflict with each other, I didn't recognized that screen, please if not a problem tell me what is your KeePass version.

Using the version available for download the configuration screen looks like this: 
![config screen](https://cloud.githubusercontent.com/assets/5115084/14411612/e6d6fee8-ff23-11e5-9db5-543ba94fa234.PNG)

The manual settings are on the custom fields  ```TOTP Seed``` thats where you place the secret key, and ```TOTP Settings``` with the format ```seconds:type``` for steam are **30:S**

**Comment by eatmybeat** [comment]
Hello Victor and others! 
Your plugin looking awesome, but I have no idea how to set it up and make it worked.

I have KP 2.33, download your plugin ver. 0.9.0.2, paste .plgx to KP folder and and I stopped.
What else I need to do to make it work? Because honest I have no idea what.
Could you do it step by step guide. I will be grateful for your help. Regards!

**Comment by victor-rds** [comment]
Just tested with the 2.33 just to be sure, no problems, just drop on the Keepass folder.

To setup TOTP right-click a Entry, then go to `Selected Entry > Setup TOTP` OR select an entry and press `Ctrl+Shift+i`, the same way the original *Tray TOTP Plugin*.

The plugin configuration can be found on `Tools` menu (Still need to fix, some the old plugin text still there)

**Comment by justxm4** [comment]
OK, got it. What should I enter in the box TOTP Seed? 

A secret key? I tried to enter all the numbers that were in the file Steamguard-myIDnumber and nothing works. This means plugin generates a password, but quite different from the mobile app.

**Comment by sfx33** [comment]
Does this no longer work with Google Two Step Verification?  I created a google application password and  and entered it as the TOTP Seed, 30 sec interval, TOTP Format 6 but when I enter the six digit code generated into the Google Verfication page it says "Wrong code. Try Again."

**Comment by incorpusyehtee** [comment]
Google application passwords are not TOTP seeds. They are for allowing apps without two-factor capability to still login to your (for instance) e-mail. Perhaps you are using Outlook 2010 and it does not have any two factor capability for authenticating for getting/sending mail. TOTP seeds are generated when you configure 2 factor authentication.

You should be able to see your 2 factor settings here: https://myaccount.google.com/signinoptions/two-step-verification

If you did not save your 2 factor TOTP then I believe you will have to contact Google.
