### ISSUE TITLE
Ctrl+T misbehaving

### ISSUE THREAD

**Issue by iyesin** [victor-rds/KeeTrayTOTP#13]
Good day.

I know it's sounds strange but `CTRL+T` working in another way than I (and all applications) expected:
- When I'm selecting some entry in `main` keepass2 window and press `CTRL+T` I'm receiving wrong code in clipboard
- When I'm selecting same entry in `main` keepass2 window and press right mouse button and selecting `Copy TOTP   Ctrl+T` everything work smooth.
- I'm pretty sure, that both events (keypress and context menu) are handled by keepass2, because `main` window minimizing after both operations (thanks to setting "Minimize main window after copying data to clipboard")

Any suggestions?

**Comment by robinvanpoppel** [comment]
@iyesin I tried to repro your this, and it probably was (partially) fixed with #11. Can you grab #14 and test if this fixes the behaviour for you?

**Comment by iyesin** [comment]
@robinvanpoppel Hey! Nice. Unfortunately I didn't managed how to build this. Can you, please, create alpha/beta/rc/whatever build for me?

**Comment by iyesin** [comment]
@robinvanpoppel thank you. I will try it today and do the report.

**Comment by iyesin** [comment]
Hello @robinvanpoppel.
I followed your instructions and it looks like that something wrong with this build: 
![screenshot_20180411_105146](https://user-images.githubusercontent.com/13554666/38606724-23166a86-3d77-11e8-96b7-6ad5f3f702a0.png)
Did I missing something?

**Comment by robinvanpoppel** [comment]
@iyesin My bad! I assumed you were using windows. I'll try and make this into a plgx file, because these are compiled by keepass itself.

**Comment by robinvanpoppel** [comment]
Here's a plgx file: [KeeTrayTOTP.zip](https://github.com/victor-rds/KeeTrayTOTP/files/1898133/KeeTrayTOTP.zip)

Please make sure to delete the .dll I previously gave you from the Keepass directory and put this file into the plugins-directory.

**Comment by iyesin** [comment]
Woohoo! @robinvanpoppel, you fixed it! It's working as expected!

**Comment by robinvanpoppel** [comment]
@iyesin Glad I could help.
@victor-rds Can you check my pull request out? And can I help you to get this released?
