### ISSUE TITLE
Update release page with new build(s)

### ISSUE THREAD

**Issue by zul-jin** [victor-rds/KeeTrayTOTP#15]
There have been a dozen or so commits to fix various issues with the plug-in since the last build from January 2016. Please upload an updated build on the release page which includes those fixes.

**Comment by robinvanpoppel** [comment]
Hi @zul-jin,

I just drafted a release against the latest version of master. See https://github.com/victor-rds/KeeTrayTOTP/releases

Please open an issue if there are any problems.
