### ISSUE TITLE
TOTP codes cannot be retrieved without a TOTP-enabled entry selected

### ISSUE THREAD

**Issue by Sanaki** [victor-rds/KeeTrayTOTP#17]
This is likely a result of the ctrl+T fixes. I've noticed that if I don't have an entry with TOTP enabled for it selected in my database, I cannot use the context menu to retrieve a TOTP code. If I select and minimize, it still works. Autotype can still properly utilize the {TOTP} placeholder without an entry selected. Most of the time, no error is shown. Occasionally the error below is.
![ktnoset](https://user-images.githubusercontent.com/1374333/39164752-af338906-4770-11e8-8c3f-539acf6622e8.jpg)

This is on 64-bit Keepass 2.38 and KeeTrayTOTP 0.9.2 (but may have been present on all other recent updates) using Windows 10. I attempted disabling all other recently updated plugins and saw no difference in behavior.

EDIT: Based on [this forum post](https://sourceforge.net/p/keepass/discussion/329220/thread/4236e391/#a6fa)'s comment about an enhanced secure edit control implementation, this may become a notably bigger issue when 2.39 is released. I won't pretend to have the experience to work out exactly what changes might be needed, but it's worth a look.

**Comment by robinvanpoppel** [comment]
@Sanaki I have a hard time reproducing this. I do get this message when I press Ctrl-T when I select an entry without TOTP-settings, but I guess this works as designed. I don't use the {TOTP} placeholder though. Can you provide me some more reproduction steps? 

P.S. I tried the latest plgx (0.9.2) with the Keepass beta and that still works for me. Fingers crossed 😃

**Comment by Sanaki** [comment]
For me, the steps to reproduce are remarkably simple. Select any entry that doesn't have a TOTP secret assigned to it, then right click the tray icon and select any entry. You should get the error message, or at least not get any modification to the clipboard. I removed all plugins other than KeeTrayTOTP just to confirm and still triggered the error reliably. I'd try to pull a console dump, but at the moment I'm not seeing any way to actually get any error visibility (probably restricted to preserve security).

I tried confirming this on linux in mono as well, but have found that the quicklaunch icon has some severe issues there, so it's not even testable, even using the icon replacements from Keebuntu.

**Comment by robinvanpoppel** [comment]
@Sanaki, thanks for the steps. I found the culprit. When clicking an item in the notify menu the currently selected password entry was used instead of the item you just clicked on. This is now fixed. I'll release a new version (0.9.3).

**Comment by Sanaki** [comment]
Confirmed fixed in linux and windows. I greatly appreciate the work you've been putting in. It makes my day to day life significantly easier.

**Comment by robinvanpoppel** [comment]
@Sanaki Glad I could help!
