### ISSUE TITLE
TOTP Seed Generation time interval is restricted to 30-60 sec

### ISSUE THREAD

**Issue by trettet** [victor-rds/KeeTrayTOTP#19]
There are some platforms online which uses a time interval beyond the range of what KeeTrayTOTP provides, one example is Garena, it uses 180 seconds or 3 minutes. KeeOtp, an alternative to KeeyTrayTOTP, however doesn't have this limitation.

**Comment by victor-rds** [comment]
@trettet AFAIK KeyTrayTOTP dosen't have this limitation, there is no option on the wizard is true, but you can set how many seconds manually by editing the `TOTP Settings` custom field, the most common value is `30;6` or 30 seconds and sis digits, change it to `180;6` and see if it works.
