### ISSUE TITLE
precompiled binary?

### ISSUE THREAD

**Issue by Offerel** [victor-rds/KeeTrayTOTP#2]
could you please provide us a compiled binary please?

**Comment by victor-rds** [comment]
You mean a DLL version? I'll see what I can do.

**Comment by Offerel** [comment]
I have found the plgx :-) Sorry, my mistake. It works now. I hope you could keep up the work.

BTW: A Steam entry is not compatible to Keepass2Android. I will write the Autor of the App on Android.
