### ISSUE TITLE
[0.9.4] TOTP format default + bug + typo

### ISSUE THREAD

**Issue by alexanderino** [victor-rds/KeeTrayTOTP#22]
In the Setup Wizard, when adding a new TOTP, the '6' value should be selected as the TOTP format default. If no value is chosen, the incomplete entry can cause a crash and KeePass exits with an error. 

Also, tabbing from the Interval value skips straight to the Server URL. This is not the case when editing an entry with a TOTP.

Finally, a minor typo: In the Server URL field, 'optional' is misspelled (2 'n' instead of 1).

Hope this is of some use.

-- alexanderino

**Comment by robinvanpoppel** [comment]
@alexanderino Thanks for reporting! I've fixed the typo and set the default TOTP length to 6. I wasn't aware that this could cause keepass to crash. Nice find! 

The change to the default TOTP size seems to fix the tab order issue as well. Are you able to build the plugin for yourself and see if you still experience the tab order issue?

**Comment by alexanderino** [comment]
@robinvanpoppel you're welcome. Unfortunately, I'm just a regular user; however, if you can provide a new build, I'll be most happy to test it and report back.

**Comment by robinvanpoppel** [comment]
I've attached a zipped up plgx. Thanks for testing!

[KeeTrayTOTP.zip](https://github.com/victor-rds/KeeTrayTOTP/files/2111627/KeeTrayTOTP.zip)

**Comment by robinvanpoppel** [comment]
Good to hear! It'll be in the next release (0.95).

**Comment by zul-jin** [comment]
Are there any plans to release v0.95 anytime soon?

**Comment by robinvanpoppel** [comment]
@zul-jin: just drafted a new release. Sorry for the delay!
