### ISSUE TITLE
Resize window automatically if QR code gets too large

### ISSUE THREAD

**Issue by mh166** [victor-rds/KeeTrayTOTP#23]
The size of the QR code depends, of course, on the amount of data stored. The longer the secret key / issuer / user are, the larger the QR code is. In the end it may be larger than the actual window. In this case, the window should be resized automatically to make it fit.

**Comment by robinvanpoppel** [comment]
@mh166: Thanks for reporting. Can you provide a reproduction for this?

**Comment by mh166** [comment]
Just take this sample entry. Right now, the QR code fits nicely in the window.

![image](https://user-images.githubusercontent.com/3167596/46965114-36f76200-d0aa-11e8-81bb-862f85c7dc10.png)

But making the issuer (for example) a bit longer, the result is getting too large to be viewed, and therefore scanned, correctly.

![image](https://user-images.githubusercontent.com/3167596/46965234-8a69b000-d0aa-11e8-9d03-975131f0d338.png)
