### ISSUE TITLE
Issue with the generated QR-Code

### ISSUE THREAD

**Issue by ophthalmos** [victor-rds/KeeTrayTOTP#24]
After successfully setting up two-factor authentication for a Google Account, the QR code generated by the plugin could not be scanned with the iOS app "Microsoft Authenticator".

**Comment by robinvanpoppel** [comment]
@ophthalmos : I do not have an iOS device in my possession, but I probably can borrow one. I do have an android device, and it did not have problems with the "Microsoft Authenticator", but they could have different implementations.

To narrow it down:
* Do you receive an error message from the app? If so, can you add these details to this issue?
* Would you mind sharing the totp settings via e-mail for an entry which generates an incorrect qr code? Maybe there's something in the secret that causes this. 
* If you have a QR code which does work: that would also make it easier to find out what's going on.

**Comment by robinvanpoppel** [comment]
Should be fixed with the PR from @haidelber. I've just created release 0.9.7.
