### ISSUE TITLE
Battle.net support?

### ISSUE THREAD

**Issue by ghost** [victor-rds/KeeTrayTOTP#3]
I am using your plugin and it works great! I wonder if you can add support for Battle.net. It would be amazing!

Cheer up!

**Comment by Steltek** [comment]
The WinAuth source code would probably come in handy here: https://github.com/winauth/winauth/blob/master/Authenticator/BattleNetAuthenticator.cs

**Comment by TrAnn3l** [comment]
It seems like you can obtain your Battle.net Secret just like you do with Steam, but there is one more step required. 

First you need a rooted phone,
then go to /data/data/com.blizzard.bma/shared_prefs/com.blizzard.bma.AUTH_STORE.xml
The File has the following layout: 
```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
<long name="com.blizzard.bma.AUTH_STORE.CLOCK_OFFSET" value="[clock offset]" />
<int name="com.blizzard.bma.AUTH_STORE_HASH_VERSION" value="10" />
<string name="com.blizzard.bma.AUTH_STORE.HASH">["encrypted" token]</string>
<long name="com.blizzard.bma.AUTH_STORE.LAST_MODIFIED" value="[timestamp]" />
</map>
```
After you got the encrypted token, you need to decrypt it. It seems like you only need to do a simple xor with a special Mask. This ruby Script can decrypt your token: https://gist.github.com/stbuehler/8616943
After that you will receive your decrypted token, which you can insert in KeeTrayTOTP with 8-digit setting and 30s timer intervall.

I already tested it and it is working, but it would be cool when KeeTrayTOTP would support the decryptingof the Battle.net Hash because it is a pain to install ruby only for this simple script.

**Comment by justxm4** [comment]
@TrAnn3l It looks like a good job, thank you for that.  But I do not understand how to do it. 
You could make a small tutorial for noobs like me? 
What program to use, and how to substitute values from the file to the code?

**Comment by TrAnn3l** [comment]
Ok, no problem.
First you need a rooted phone (There a many tutorials on the web how to root a phone) and the [Battle.net Authenticator](https://play.google.com/store/apps/details?id=com.blizzard.bma) installed and setted up.
Now you need a Root File Manager. I will use [this one](https://play.google.com/store/apps/details?id=com.acr.rootfilemanager&hl=de).
Open your Root File Manager and go to /data/data/com.blizzard.bma/shared_prefs. 
There is a file called com.blizzard.bma.AUTH_STORE.xml. Try to open it, when it is not possible, copy it to a Folder where you don't need Root permissions, e.g. your Downloads Folder. Now you should be able to open the file. 

The File will have the following layout:

```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
<long name="com.blizzard.bma.AUTH_STORE.CLOCK_OFFSET" value="[clock offset]" />
<int name="com.blizzard.bma.AUTH_STORE_HASH_VERSION" value="10" />
<string name="com.blizzard.bma.AUTH_STORE.HASH">["encrypted" token]</string>
<long name="com.blizzard.bma.AUTH_STORE.LAST_MODIFIED" value="[timestamp]" />
</map>
```

Copy or write down the "encrypted" token.
Now you need to install Ruby ,download the script and run it.

**Debian and Similar**
Just do a simple `sudo apt-get install ruby` and you should have ruby.
Now you need to Download the Script with `wget https://gist.githubusercontent.com/stbuehler/8616943/raw/f46f6775afa6be01ba321697a973c9c484046411/bma2otp.rb`

**Windows**
There are many Installers for ruby outside. Like [this one](http://rubyinstaller.org/).
Download the installer and install ruby.
Now you need to Download the script. Just go over [here](https://gist.githubusercontent.com/stbuehler/8616943/raw/f46f6775afa6be01ba321697a973c9c484046411/bma2otp.rb) with your browser, right-click and select `save as...`
After you got the script you must start the console with WIN+R, type `cmd` and press enter. Now you need to go to the directory where you downloaded the script.

Now you only need to run the script with `ruby bma2otp.rb`.
It will ask for the "encrypted" token so just insert it here and press Enter.
It will return something similar to that:
```
otpauth://totp/EU-1234-1234-1234:EU-1234-1234-1234?secret=ABC123ABC123ABC123ABC123ABC1234&issuer=EU-1234-1234-1234&digits=8
'qrencode' failed, maybe binary is not available?
```
The part after secret is the right one to go. Just enter it KeeTrayTOTP and select 8 digits. Finished.

**Comment by justxm4** [comment]
Thank you @TrAnn3l , but for me does not work (Windows 7 SP1 32bit).
What did I do?
1) I installed Ruby from your link.
2) I created a notepad file with the code saved as `bma2otp.rb`.
3) I tried to run a script by cmd failed.
`E:\>ruby bma2otp.rb
ruby: No such file or directory -- bma2otp.rb <LoadError>`

And yes, the file was located in the specified location cmd.

4) I tried another way - Drag and drop  `bma2otp.rb`  directly on `C:\Ruby23\bin\ruby.exe`
   The script worked and ask me about encrypted token so I typed `<string name="com.blizzard.bma.AUTH_STORE.HASH">XXXXXX</string>` from my token file. 
 
After pressing ENTER the script in less than a second the script exits with no answers..

**Comment by victor-rds** [comment]
@justxm4 I never used ruby (at least not via cli), but knowing how messed windows cli can be, try using full path when possible:
`C:\> ruby E:\full\path\bma2otp.rb`

**Comment by TrAnn3l** [comment]
You only need to use the `XXXXXXXXXXX` from the following`<string name="com.blizzard.bma.AUTH_STORE.HASH">XXXXXX</string>`

**Comment by justxm4** [comment]
The same error. Later I'll try to do it on another computer.
![scr1](https://cloud.githubusercontent.com/assets/19262476/16988145/b8909e84-4e8f-11e6-9ebc-7c9f4342981a.jpg)

**Comment by TrAnn3l** [comment]
try `C:\Ruby23\bin\ruby.exe E:\full\path\bma2otp.rb`

**Comment by justxm4** [comment]
Thank you for helping guys, everything works very well.  I had to get this script as a zip [.](https://gist.github.com/stbuehler/8616943) Then it turned on without a problem, rewrite the code and worked. The problem is that it disappears in less than a second, and I had to record the movie to catch this code.
Thanks again for your time and attention. Best regards!

**Comment by Creased** [comment]
Hey, I've developed an online tool (frontend process, no data is collected) to perform BMA to OTP conversion, tool and process are described [here](https://vps.bmoine.fr/bma-decoder/).

Using the [first tool](https://vps.bmoine.fr/bma-decoder/), you can perform conversion of BMA to TOTP secret, if you want to use this token on FreeOTP or Google Authenticator (non-tested), you can use [this other tool](https://vps.bmoine.fr/otp-qrcode/) to generate a quick QR-Code from your decoded token, username, service icon, etc. (please note that a dedicated template has been implemented 😃).

All these tools are open source and can be forked from here:

| Project                                 | URL                                | Sources                           |
|-----------------------------------------|------------------------------------|-----------------------------------|
| Battle.net Mobile Authenticator Decoder | https://vps.bmoine.fr/bma-decoder/ | https://git.bmoine.fr/bma-decoder |
| OTP QR-Code Generator                   | https://vps.bmoine.fr/otp-qrcode/  | https://git.bmoine.fr/otp-qrcode  |

Feel free to use/share/fork and don't hesitate to contribute to these projects! 😃

*Happy Hacking*

**Comment by Sanaki** [comment]
Worked perfectly. Now if only we could get Trion and Square Enix authenticators working too.

**Comment by robinvanpoppel** [comment]
I am going through the old issues to see which ones are still relevant. Looks like this one can be closed. Please open an issue if you feel this is not the case.

**Comment by Sanaki** [comment]
While I agree it is no longer needed, some notation in the documentation near the steam section (or even just a link to this issue) would help newer users find what they need. Most users won't think to look through closed issues, or even know how in many cases.

**Comment by robinvanpoppel** [comment]
@Sanaki I agree we should aim to make this information more accessible. I think the wiki would be a good place indeed. Another alternative would be the readme.md as it already covers retrieving the steam key,

**Comment by beerisgood** [comment]
So it's not possible to add this as easy solution in KeeTrayTOTP ?

**Comment by Sanaki** [comment]
What are you asking? I have blizzard and steam OTP functioning via this plugin using the methods included in this issue.

**Comment by beerisgood** [comment]
@Sanaki without the solution from @Creased ?

**Comment by Sanaki** [comment]
Ahhh, you're saying you want that code incorporated into KeeTrayTOTP rather than requiring an external website to handle that stage. I can support that concept. I'd recommend opening a new issue to request that though, as it's a bit of a topic shift.

**Comment by beerisgood** [comment]
@Sanaki: https://github.com/victor-rds/KeeTrayTOTP/issues/29

**Comment by beerisgood** [comment]
For all WinAuth user:

With the great [website](https://vps.bmoine.fr/otp-qrcode/) from [Creased ](https://github.com/victor-rds/KeeTrayTOTP/issues/3#issuecomment-302715329) you can migrate to your Android app (andOTP for example) !

You got the needed Base32-Encoded secret from WinAuth if you export the Battle.net in plaintext. In that you see the following output:
otpauth://totp/BattleNet:Battle.net?secret=**YOUR CODE**&digits=8&issuer=BattleNet&serial=YOUR SERIAL

The "**YOUR CODE**" is the needed Base32-Encoded secret.

**Comment by anonymous1184** [comment]
For people who like me uses iOS (or don't want to mess around with that uber-complicated option) a simple CLI that only requires serial and restore code can be found here:

https://github.com/jleclanche/python-bna

Is as easy as:

```
bna restore US-1234-1234-1234 ABCDE12345
bna show-url
```
Actually the "show-url' is optional, `bna.conf` stores the secret and can be copied from there. Thus my recommendation is to delete the file after copying the secret.

OTOH, implementing it can be done [based on the code](https://github.com/jleclanche/python-bna/blob/2f79843d7a93c3c49168dd81de42bda7793d5e5e/bna/http.py#L116), but that's up to the project owner,
