### ISSUE TITLE
Option to _not_ use Tray

### ISSUE THREAD

**Issue by ccoenen** [victor-rds/KeeTrayTOTP#33]
I know this goes against the name of this plugin, but hear me out :-D

Since the original inception of this plugin, the world has changed dramatically. Back in the day, you'd use TOTP on 2-3 websites at most. Now I have configured ~20 accounts for TOTP. The Systray right-click-menu looks ridiculous and personally, I don't use it this way.

I would like to be able to not have the TOTP entries listed in that menu.

**Comment by Offerel** [comment]
Simple uncheck under Tools > Tray TOTP Plugin > Settings > Context Menu > Tray Menu

**Comment by ccoenen** [comment]
Oh now _that_s embarrassing :-D Thanks for the explanation!
