### ISSUE TITLE
Plugin 0.97-Beta doesn't work with latest KeePass 2.42.1

### ISSUE THREAD

**Issue by kpleines** [victor-rds/KeeTrayTOTP#37]
I updated to the latest KeePass Version 2.42.1. Since than, I got the following Exception at startup:

Folgendes Plugin ist inkompatibel mit der aktuellen KeePass-Version: KeeTrayTOTP.dll
Is there an update of KeeTrayTOTP planed to fix this error or is there an worksround?

Thanks

![grafik](https://user-images.githubusercontent.com/12126050/58047147-ad2fdb80-7b47-11e9-881e-0a7e6cdbda31.png)

**Comment by robinvanpoppel** [comment]
Can you check what version of keetraytotp you're running?
