### ISSUE TITLE
Plugin Crashes When "TOTP Seed" Field Already Exists

### ISSUE THREAD

**Issue by shad0whawk** [victor-rds/KeeTrayTOTP#38]
The plugin crashes when I try to setup/modify an entry with an existing TOTP Seed value populated from another TOTP program.   In my case, I created it with Strongbox which uses the same syntax, but it isn't recognized by your plugin as setup.  When I click "Setup TOTP" for this entry, it causes an exception error.

**Comment by shad0whawk** [comment]
Well I figured out the issue.  It crashes because the "TOTP Settings" field does not exist so maybe add some error handling or other mechanism to handle this.

**Comment by robinvanpoppel** [comment]
Is it possible for you to set up totp settings via strongbox in an empty kdbx file and upload the file here? That way I can reproduce the error.

**Comment by Thurion** [comment]
I noticed the error when I manually renamed a custom field to "TOTP Seed" and didn't add "TOTP Settings". It's a rare case that should not happen often but some kind of error handling would be nice.

**Comment by robinvanpoppel** [comment]
I tried to get the plugin to crash by removing TOTP Seed / TOTP Settings separately and putting some fake data in the seed, but got error messages with "Error, bad seed!" / "Error, bad settings!". 

If you still experience problems please reopen this issue and provide data so I can reproduce 😄
