### ISSUE TITLE
Seeing double of the "Tray TOTP Plugin" menus

### ISSUE THREAD

**Issue by thakyZ** [victor-rds/KeeTrayTOTP#39]
I don't know if this is normal for everyone else, or if it's completely my side, or even if it's been reported yet. But I have been having this issue persist for some time now.
When I right click any entry and look down the menu there is one menu that says
"Tray TOTP Plugin"
And another that also says "Tray TOTP Plugin"
As shown here in this picture:
![image](https://user-images.githubusercontent.com/950594/63044968-31aea380-be84-11e9-85ee-6a8eb63564e4.png)

**Comment by robinvanpoppel** [comment]
Hi @thakyZ, The plugin might have been loaded twice. Can you check your `Keepass\plugins` folder for any duplicated .plgx / dll's?

**Comment by thakyZ** [comment]
Oh yea I still had one int he KeePass Password Safe 2 folder, surprisingly outside the Plugins folder.
