### ISSUE TITLE
Supporting 7 digit TOTP

### ISSUE THREAD

**Issue by TheB1gG** [victor-rds/KeeTrayTOTP#40]
Hi,
would it be possible to support 7 digit totp?
Sadly that is needed for everthing which uses authy. There is already a implementation, maybe that can be used?
https://github.com/keepassxreboot/keepassxc/pull/2517

**Comment by robinvanpoppel** [comment]
I can certainly look into this in the near future :)

**Comment by robinvanpoppel** [comment]
Hi @TheB1gG, please take a look at the latest version as of now (0.99) and let me know if you experience any problems.

**Comment by TheB1gG** [comment]
Hi @robinvanpoppel ,
it does work for me.
Thank you

**Comment by schnudeldudel** [comment]
awesome. thanks for this new feature!!!
