### ISSUE TITLE
Use of the PlgxTool tool

### ISSUE THREAD

**Issue by lxitdn** [victor-rds/KeeTrayTOTP#43]
How do I use the Plgxtool tool in other Keepass plugin source projects? Can you teach me to use it? I am a newbie, I want to learn, I want to modify the language of several plugins, I can change it to my native language, but I will not use the Plgxtool tool.

**Comment by robinvanpoppel** [comment]
Hi @lxitdn,

We do consume PlgxTool to build a plgx file after building the plugin. See commit 822dff336ed4bac301e86eeb310a4693cd7f4b58 for how it was added to this plugin. 

Please take a look at the repository for PlgxTools for more information.
https://github.com/dlech/KeePassPluginDevTools/tree/master/PlgxTools
