### ISSUE TITLE
Extract Steam key on Android using an Emulator

### ISSUE THREAD

**Issue by Thurion** [victor-rds/KeeTrayTOTP#45]
Would it be possible to install the Steam app on an Android Emulator to extract the secret key?

**Comment by Sanaki** [comment]
If that's your preference, check this out instead:
https://github.com/victor-rds/KeeTrayTOTP/blob/master/docs/secret_sda/steam_desktop_authenticator_sda.md

**Comment by Thurion** [comment]
I didn't see that document. But the readme mentions `this have the drawback of disabling the mobile app`. Maybe the readme needs an update?
Would be nice if there was a link in the readme to the file you mentioned.

**Comment by Sanaki** [comment]
That file was only very recently committed, it's on the dev's to-do list. But yeah, the problem in general is that steam doesn't want you to have multiple active authenticators at the same time. In fact, almost no one does. The way this project works isn't the way people want TOTP to be used. We just happen to disagree with them. Using an android emulator wouldn't change that, it still won't want multiple active authenticators. The only way I could see it working is if you have an android phone already, you figure out how to make and restore an adb backup of the steam app to copy your active auth setup onto the emulator (and it may not work even if you do), then get it that way.

**Comment by Thurion** [comment]
Now I get it: The problem is that they allow only one authenticator in general. Thanks for elaborating 👍
