### ISSUE TITLE
Twitch.tv support

### ISSUE THREAD

**Issue by DormantCheese** [victor-rds/KeeTrayTOTP#48]
Is it possible to add support for Twitch.tv's 2FA seed?

I added 2FA to my Twitch account and it uses Authy to generate TOTPs. Using the method to export Authy TOTP secrets found [here](https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93), I exported the secret for my Twitch account. When I copy/pasted it to KeeTrayTOTP's TOTP Seed field in KeePass, I get an error saying Invalid Character with a list of characters containing 0, 1, and 8. I'm guessing Twitch's seed is not Base32. Their seed is all numeric and 64 characters long.

Other things to note in case they're relevant:
- Twitch uses a 20 second interval instead of the normal 30 seconds
- Twitch uses 7 digits

Please let me know if I can provide any further info that would help adding support for Twitch.tv 2FA.

**Comment by Sanaki** [comment]
I can support this request. Twitch is the only reason I still have authy, and I would absolutely love to get rid of it.

**Comment by neothematrix** [comment]
I'm succesfully using TrayTOTP with Twitch, I used a slightly different method (probably more complex to be honest) to extract the seed from Authy as described [here](https://randomoracle.wordpress.com/2017/02/15/extracting-otp-seeds-from-authy/).
If you read the article, you'll know that the extracted seed could be hex or base64 encoded (the latter is Twitch case, hence the very long seed), but we need base32, so there is one comment that has a nice Python oneliner function to convert it back to base32:

`import base64, binascii`
`base64.b32encode(binascii.unhexlify(extracted_seed)`

subsitute "extracted_seed" with your seed of course.

And be aware, **interval is actually 10 seconds**, not 20 as Authy shows, so enter "10" as interval and 7 digits when configuring TrayTOTP, and don't freak out if the Authy and TrayTOTP OTP codes are different, try to login on Twitch anyways, in my case, they both work (for some reason I still need to understand).

**Comment by robinvanpoppel** [comment]
I'm not a twitch user. Would one of you be able to create a PR and improve the documentation in this area?

**Comment by tendererdegree** [comment]
This is not an issue. If you follow the steps provided by neothematrix for extracting an authy secret and you set the totp settings correctly, you can already achieve twitch.tv support

**Comment by robinvanpoppel** [comment]
Closing this as indicated by @tendererdegree
