### ISSUE TITLE
Why "Copy TOTP" is now in submenu?😭

### ISSUE THREAD

**Issue by cuoe** [victor-rds/KeeTrayTOTP#49]
Why "Copy TOTP" is now in secondary menu? it's inconvenient to use. (setting is correct.)
I always use mouse, not hotkey.
Could you please put it into the first menu? thanks

**Keepass 2.40, KeeTrayTOTP 0.95:**
![2 40](https://user-images.githubusercontent.com/26758380/71561952-75631c00-2ab8-11ea-98ce-a4ffd55c57ca.png)
====
**Keepass 2.43, KeeTrayTOTP 0.99:**
![2 43](https://user-images.githubusercontent.com/26758380/71561962-91ff5400-2ab8-11ea-9066-1e028e2c656f.png)
====

**Comment by robinvanpoppel** [comment]
Hi @cuoe, I'm sorry about that. It was done because of a breaking change in Keepass (around version 2.42).

As taken from the `Providing Menu Items` section in the [plugin guidelines section](https://keepass.info/help/v2_dev/plg_index.html) on what plugins can do with menu's:

> Many plugins provide menu items (with subitems, if necessary) in prominent locations like the 'Tools' menu, the entry context menu, etc. Such a menu item can be supplied to KeePass by overriding the GetMenuItem method of your plugin class (which derives from the Plugin base class). In this method, the plugin can construct and return a ToolStripMenuItem, which KeePass will then show in the appropriate location.
>
> Users should be able to associate the menu item with your plugin. Typically, plugins set the text of the menu item to the name of the plugin or a string that starts with the name of the plugin. For example, a plugin 'Abcd' that wants to provide one menu item only (for accessing the plugin options) could set the text of the menu item to 'Abcd Options'. **If the plugin supports multiple commands, set the menu item's text to the plugin name (e.g. 'Abcd') and add a subitem for each command.**
```
