### ISSUE TITLE
Increase period from 60 to 180

### ISSUE THREAD

**Issue by rasa** [victor-rds/KeeTrayTOTP#50]
Shouldn’t we increase period from 60 to 180 in
https://github.com/victor-rds/KeeTrayTOTP/blob/9bed0c45d86e3604dddac1fc5240a576d8b4f5e1/KeeTrayTOTP/SetupTOTP.cs#L96
per 
https://github.com/victor-rds/KeeTrayTOTP/commit/355defa85b83dfdeb21d8d62b967903e69b564f3

**Comment by robinvanpoppel** [comment]
I think you're totally right. Created PR #51 for this. Care to take a look?

**Comment by robinvanpoppel** [comment]
Release a new version (0.100) to address this
