### ISSUE TITLE
How should I translate these keywords?

### ISSUE THREAD

**Issue by lxitdn** [victor-rds/KeeTrayTOTP#59]
How should I translate these keywords? I searched the source code, I couldn't find the keywords, I don't know how to translate them, as shown below

![QQ截图20200131170115](https://user-images.githubusercontent.com/16263881/73526280-db421b00-444b-11ea-96ea-4ee1730bd558.jpg)

**Comment by robinvanpoppel** [comment]
The values in this dropdown are pre-existing field names that you've used on other password entries. I never had the need to change this, but I guess this allows you to choose a field name to store the seed and the totp settings. The plugin will then use that field name to lookup the seed and settings for your database entry. If you don't like this name you can type your own, but if you have pre-existing TOTP settings stored the plugin will not be able to find them.

**Relevant code that populates the dropdowns.**:
https://github.com/victor-rds/KeeTrayTOTP/blob/226f50bc0fb72009372868067f55eb28b0a973f3/KeeTrayTOTP/FormSettings.cs#L279-L293

Off topic:
> I don't have any experience with the translation part of the plugin, but would like to get accustomed to it in order to allow you to translate it. What process did you go through to get the other translations? I know most of the texts are coming from a resource.

**Comment by lxitdn** [comment]
> The values in this dropdown are pre-existing field names that you've used on other password entries. I never had the need to change this, but I guess this allows you to choose a field name to store the seed and the totp settings. The plugin will then use that field name to lookup the seed and settings for your database entry. If you don't like this name you can type your own, but if you have pre-existing TOTP settings stored the plugin will not be able to find them.
> 
> **Relevant code that populates the dropdowns**:
> https://github.com/victor-rds/KeeTrayTOTP/blob/226f50bc0fb72009372868067f55eb28b0a973f3/KeeTrayTOTP/FormSettings.cs#L279-L293
> 
> Off topic:
> 
> > I don't have any experience with the translation part of the plugin, but would like to get accustomed to it in order to allow you to translate it. What process did you go through to get the other translations? I know most of the texts are coming from a resource.

I downloaded your source code and then translated it myself using VC software

**Comment by robinvanpoppel** [comment]
Thanks for your comment on the translation itself. On the issue itself: As you can specify the name of the entries yourself in the configuration I don't think it is something you can translate. I'll close this issue.
