### ISSUE TITLE
Manually changing the settings (to nonsense) can prevent the user from opening his database

### ISSUE THREAD

**Issue by dannoe** [victor-rds/KeeTrayTOTP#62]
**Steps to reproduce this bug:**

- Change the TOTP settings of an entry manually to: ``0;5`` (both values are not allowed)
- Reopen database.
- ``System.DivideByZeroException`` will be thrown and the KeePass GUI won't be loaded correctly:

![grafik](https://user-images.githubusercontent.com/7450586/77832476-56633d00-712e-11ea-87c2-0631bd07f192.png)

**The problem:**

The ``SettingsValidate`` method even returns true if the settings are not valid.

**Comment by robinvanpoppel** [comment]
@dannoe: Thanks for taking the time to contribute a fix as well. I will take a look at your PR.
