### ISSUE TITLE
Feature Request: Hide expired entries

### ISSUE THREAD

**Issue by sir106** [victor-rds/KeeTrayTOTP#66]
would be great if all expired entries would be hidden from the tray TOTP list.

**Comment by robinvanpoppel** [comment]
@sir106 

I've added a PR (#82) to fix this. A plgx file can be found under artifacts in [this build](https://github.com/victor-rds/KeeTrayTOTP/pull/82/checks?check_run_id=561829078). Could you check it out, and report whether this is what you meant?

**Comment by sir106** [comment]
Hey Robin ( @robinvanpoppel ),

many thanks for creating this PR - tested it successful; works perfect! expired entries are no longer shown; all others are still visible...

Thanks!

SVEN
