### ISSUE TITLE
Misbehaving fonts in all dialogs

### ISSUE THREAD

**Issue by avoidik** [victor-rds/KeeTrayTOTP#75]
Hi,

Just small notice regarding UI fonts in all dialogs, the labels text doesn't fit into the fields.

![labels emerges](https://user-images.githubusercontent.com/6435932/78457881-2bd92d00-76b6-11ea-851d-adaabc4af5e5.png)

**Comment by avoidik** [comment]
looks like the problem is on my end, DPI has been set to 125%

**Comment by avoidik** [comment]
the fix was

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
"C:\\Program Files (x86)\\KeePass Password Safe 2\\KeePass.exe"="DPIUNAWARE"
```

**Comment by dannoe** [comment]
see #8
